### ISSUE TITLE
exo config format

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/egoscale#181]
in the issue https://github.com/exoscale/egoscale/issues/179 we want to leave from `cloudstack.ini`configuration file. So what can be the new format of our new config file

Advantage:
 - usable with **spf13/viper**
 - manage accounts more easily
 - create an environment for each account

**Comment by pierre-emmanuelJ** [comment]
potential format can be:

JSON
```json
{
    "accounts": [
        {
            "name": "account1",
            "organisation-name": "Exosclale-1",
            "username": "toto@exoscale.ch",
            "key": "EXO.....",
            "secret": "secretekey....."
        },
        {
            "name": "account2",
            "organisation-name": "Exosclale-2",
            "username": "otot@exoscale.ch",
            "key": "EXO.....",
            "secret": "secretekey....."
        }  
    ]
}
```

**Comment by pierre-emmanuelJ** [comment]
**OR**

```toml
[[accounts]]
name = "account1"
key = "..."

[[accounts]]
name = "derp"
...
```

**Comment by pierre-emmanuelJ** [comment]
```toml
[[accounts]]
name = "prod"
endpoint = "https://api.exoscale.ch/compute"
key = "EXOxxxxxxxxxxxxxxxx53e5f4"
secret = "5ze-xxxxxxxxxxxxxxxxxxxxxxxM"
defaultZone = "ch-gva-2"
isDefault = true

[[accounts]]
name = "preprod"
endpoint = "https://fsdsdfdspi.exoscale.ch/compute"
key = "EXOxxxxxxxxxxx066"
secret = "xLxxxxxxxxxx0sg"
defaultZone = "ch-dk-2"
isDefault = false

[[accounts]]
name = "fail" 
endpoint = "https://fdssdfsapi.exoscale.ch/compute"
key = "EXO8xxxxxxxxxxxxxxxxxxx66___"
secret = "xLVkexxxxxxxxxxxxxbpo0sg___"
isDefault = false

```
