### ISSUE TITLE
exo config show to display current config

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#246]
at the moment, `exo config show` wants an explicit configuration to be displayed. It'd be nice to have the default one.

```console
% exo config show
(help)

% exo config list
- foo [default]

% exo config show foo
what I wanted in the first play
```

**Comment by pierre-emmanuelJ** [comment]
👍

**Comment by greut** [comment]
in b58247244021c18ac4b1e596a82b1ab9fb353f22

```toml
defaultaccount = "cloudstack-testing"

[[accounts]]
  account = "cloudstack-testing"
  defaultZone = "at-vie-1"
  endpoint = "https://ppapi.exoscale.ch/compute"
  key = "EXOdae2afd26b333016a7d58ecf"
  name = "cloudstack-testing"
  secret = "××××××××××"
```

produces.

```
% exo config show cloudstack-testing
Name:         cloudstack-testing
API Key:      EXOdae2afd26b333016a7d58ecf
API Secret:   ××××××××××
Account:      cloudstack-testing
Default zone: at-vie-1
Endpoint:     https://ppapi.exoscale.ch/compute
DNS Endpoint: https://ppapi.exoscale.ch/dns
```
